name: CI Testing

on:
  push:
  pull_request:

env:
  PYTEST_ADDOPTS: "--color=yes"

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os:  [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            python-version: "3.8"
          - os: macos-latest
            python-version: "3.8"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      if: ${{ ! contains(matrix.os, 'windows') }}
      with:
        python-version: ${{ matrix.python-version }}

    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      if: ${{ contains(matrix.os, 'windows') }}
      with:
        update-conda: true
        python-version: ${{ matrix.python-version }}
        conda-channels: conda-forge

    - name: Install conda packages
      if: ${{ contains(matrix.os, 'windows') }}
      run: |
        conda install pip pyyaml fiona shapely nomkl

    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip black codecov
        python -m pip install .[dev]

    - name: Lint with black
      run: |
        black --check .

    - name: Test with pytest
      run: |
        coverage run --source=sentinelsat -m pytest -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      env:
        OS: ${{ matrix.os }}
        PYTHON: ${{ matrix.python-version }}
      with:
        # token: ${{ secrets.CODECOV_TOKEN }}  # not required for public repos
        env_vars: OS,PYTHON
        fail_ci_if_error: true
