name: Weekly live testing
# Runs test without pre-recorded cassettes against the live server on a weekly basis

on:
  schedule:
    # at 00:00 every Sunday
    - cron:  '0 0 * * 0'

jobs:
  run-live-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip
        python -m pip install .[dev]

    - name: Delete cassettes
      run: |
        ./tests/fixtures/clean_cassettes.sh
    
    - name: Server health check
      id: health-check
      run: |
        sentinelsat --info | grep "DHuS version"
    
    - name: Run tests and re-record cassettes
      if: steps.health-check.conclusion == 'success'
      env:
        DHUS_USER: ${{ secrets.DHUS_USER }}
        DHUS_PASSWORD: ${{ secrets.DHUS_PASSWORD }}
      run: |
        pytest --vcr-record new_episodes -vvv
    
    - name: Test with the recorded cassettes
      run: |
        pytest -vvv
      
    - name: Upload new cassettes as an artifact
      uses: actions/upload-artifact@v2
      if: always() && steps.health-check.conclusion == 'success'
      with:
        name: fixtures
        path: tests/fixtures/

    - name: Create an issue if tests failed
      uses: JasonEtco/create-an-issue@v2
      if: failure() && steps.health-check.conclusion == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/live-test-failure-template.md
